In [1]:
import pandas as pd
import numpy as np
nigeria=pd.read_csv("../data/nigeria.csv",skipfooter=10)
nigeria.head()

/tmp/ipykernel_61080/2066773135.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  nigeria=pd.read_csv("../data/nigeria.csv",skipfooter=10)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M
0,2015,1,25.23,29.25,22.06,7.19,0.0,68.26,1.73,2.61,100.86,13.36
1,2015,2,26.16,29.41,22.87,6.54,0.0,73.23,1.42,1.95,100.94,15.37
2,2015,3,25.66,29.02,22.63,6.39,0.0,78.71,1.69,2.33,101.06,15.98
3,2015,4,24.11,27.27,19.92,7.35,0.0,63.66,2.15,3.80,101.09,11.65
4,2015,5,23.40,27.28,18.18,9.10,0.0,59.45,1.88,3.48,101.03,10.40

In [2]:
# missing value
nigeria.replace(-999,np.nan,inplace=True)
print(f" Messing Value found:\n {nigeria.isnull().sum()}")

 Messing Value found:
 YEAR           0
DOY            0
T2M            0
T2M_MAX        0
T2M_MIN        0
T2M_RANGE      0
PRECTOTCORR    0
RH2M           0
WS2M           0
WS2M_MAX       0
PS             0
QV2M           0
dtype: int64

In [3]:
# date conversion
nigeria["DATE"]=pd.to_datetime(nigeria["YEAR"]*1000+nigeria["DOY"],format= "%Y%j")
nigeria["MONTH"]=nigeria["DATE"].dt.month
nigeria.set_index("DATE",inplace=True)
nigeria.head()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,MONTH
DATE,,,,,,,,,,,,,
2015-01-01,2015,1,25.23,29.25,22.06,7.19,0.0,68.26,1.73,2.61,100.86,13.36,1
2015-01-02,2015,2,26.16,29.41,22.87,6.54,0.0,73.23,1.42,1.95,100.94,15.37,1
2015-01-03,2015,3,25.66,29.02,22.63,6.39,0.0,78.71,1.69,2.33,101.06,15.98,1
2015-01-04,2015,4,24.11,27.27,19.92,7.35,0.0,63.66,2.15,3.80,101.09,11.65,1
2015-01-05,2015,5,23.40,27.28,18.18,9.10,0.0,59.45,1.88,3.48,101.03,10.40,1

In [4]:
# Save cleaned data
nigeria.to_csv('../data/nigeria_clean.csv', index=False)
print(" Cleaned data saved to: data/nigria_clean.csv")

 Cleaned data saved to: data/nigria_clean.csv

In [ ]:
# Monthly Temperature Line Chart
import matplotlib.pyplot as plt
# resample monthely averagy
monthly_temp=nigeria["T2M"].resample('ME').mean()
plt.figure(figsize=(12,6))
plt.plot(monthly_temp,label="Mean Temp ",color='orange')
# annotate the hotest month in 2023
hottest_2023=monthly_temp["2023"].idxmax()
temp_max=monthly_temp['2022'].max()
plt.annotate(f"Peack heat at 2023 :{temp_max:.2f}",
             xy=(hottest_2023,temp_max),
             xytext=(hottest_2023,temp_max+2),
             arrowprops=dict(facecolor='black',shrink=0.05))
plt.title('Nigeriya: Monthly Temperature Trends (2015-2026)')
plt.ylabel('Temperature (°C)')
plt.show()

In [ ]:
# Resample to Monthly total rainfall
monthly_rain = nigeria['PRECTOTCORR'].resample('ME').sum()

plt.figure(figsize=(12, 6))
plt.bar(monthly_rain.index, monthly_rain.values, color='skyblue', width=20) # type: ignore

# Identify the peak rainy season (example: finding the highest bar)
peak_month = monthly_rain.idxmax()
peak_value = monthly_rain.max()

plt.annotate('Peak Rainy Season', 
             xy=(peak_month, peak_value),  # type: ignore
             xytext=(peak_month, peak_value + 50), # type: ignore
             arrowprops=dict(arrowstyle='->', lw=2))

plt.title('Nigeriya: Monthly Total Precipitation')
plt.ylabel('Rainfall (mm)')
plt.show()